### ISSUE TITLE
What indicators of network telemetry can be obtained through Panoptes stream?

### ISSUE THREAD

**Issue by zhangnazg** [yahoo/panoptes-stream#1]
How to obtain the actual packet loss, delay and other indicators?

**Comment by mehrdadrad** [comment]
It collects the vender's metrics through different protocols (gNMI, Cisco MDT and Juniper JTI), like interface counters or BGP.
If you're looking for the latency metrics, I recommend this open source: https://github.com/yahoo/UDPing
